# Inserts a blank line between shell prompts
add_newline = true

# Set timeout for commands executed by starship
command_timeout = 1000

# Replace the "â¯" symbol in the prompt with the "âœ"
[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ–](bold red) "

# Replace the default elixir symbol
[elixir]
symbol = "ğŸ”® "

# # Replace the default Node.js symbol
[nodejs]
format = "via [ï¢˜ $version](bold green) "

[gcloud]
disabled = true
